# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dumper.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from functions import *

class Ui_DiamondDumper(object):
    def setupUi(self, DiamondDumper):
        DiamondDumper.setObjectName("DiamondDumper")
        DiamondDumper.resize(980, 687)
        DiamondDumper.setMinimumSize(QtCore.QSize(980, 500))
        DiamondDumper.setMaximumSize(QtCore.QSize(980, 875))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(35, 38, 41))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        DiamondDumper.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        DiamondDumper.setFont(font)
        DiamondDumper.setAutoFillBackground(False)
        DiamondDumper.setStyleSheet("QLineEdit,\n"
"QComboBox,\n"
"QDateTimeEdit,\n"
"QSpinBox,\n"
"QDoubleSpinBox {\n"
"  color: #1de9b6;\n"
"  background-color: #31363b;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;\n"
"}\n"
"\n"
"QWidget {\n"
"  background-color: #232629;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"QGroupBox,\n"
"QFrame {\n"
"  background-color: #232629;\n"
"  border: 2px solid #4f5b62;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QRadioButton::indicator,\n"
"QCheckBox::indicator {\n"
"  width: 16px;\n"
"  height: 16px;\n"
"  border: 2px solid #1de9b6;\n"
"  border-radius: 0;\n"
"  transform: rotate(45deg);\n"
"  transform-origin: center;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked,\n"
"QCheckBox::indicator:checked {\n"
"  background-color: #1de9b6;\n"
"  border-color: #1de9b6;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover,\n"
"QCheckBox::indicator:hover {\n"
"  border-color: rgba(29, 233, 182, 0.8);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:hover,\n"
"QCheckBox::indicator:checked:hover {\n"
"  border-color: #1de9b6;\n"
"}")
        DiamondDumper.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(DiamondDumper)
        self.centralwidget.setWhatsThis("")
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 951, 221))
        self.tableWidget.setStyleSheet("border-color: #1de9b6;\n"
"color: rgb(222, 0, 0);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.submit_single_token_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_single_token_button.setGeometry(QtCore.QRect(240, 10, 80, 31))
        self.submit_single_token_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.submit_single_token_button.setObjectName("submit_single_token_button")
        self.sync_button = QtWidgets.QPushButton(self.centralwidget)
        self.sync_button.setGeometry(QtCore.QRect(380, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sync_button.setFont(font)
        self.sync_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.sync_button.setObjectName("sync_button")
        self.import_bulk_button = QtWidgets.QPushButton(self.centralwidget)
        self.import_bulk_button.setGeometry(QtCore.QRect(500, 10, 80, 31))
        self.import_bulk_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.import_bulk_button.setObjectName("import_bulk_button")
        self.bot_manager_text_input = QtWidgets.QTextEdit(self.centralwidget)
        self.bot_manager_text_input.setGeometry(QtCore.QRect(10, 60, 221, 31))
        self.bot_manager_text_input.setStyleSheet("  border-color: #1de9b6;")
        self.bot_manager_text_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bot_manager_text_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.bot_manager_text_input.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.bot_manager_text_input.setObjectName("bot_manager_text_input")
        self.single_token_submittion_text_input = QtWidgets.QTextEdit(self.centralwidget)
        self.single_token_submittion_text_input.setGeometry(QtCore.QRect(10, 10, 221, 31))
        self.single_token_submittion_text_input.setStyleSheet("  border-color: #1de9b6;")
        self.single_token_submittion_text_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.single_token_submittion_text_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.single_token_submittion_text_input.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.single_token_submittion_text_input.setObjectName("single_token_submittion_text_input")
        self.telegram_chat_id_text_input = QtWidgets.QTextEdit(self.centralwidget)
        self.telegram_chat_id_text_input.setGeometry(QtCore.QRect(240, 60, 131, 31))
        self.telegram_chat_id_text_input.setStyleSheet("  border-color: #1de9b6;")
        self.telegram_chat_id_text_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.telegram_chat_id_text_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.telegram_chat_id_text_input.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.telegram_chat_id_text_input.setObjectName("telegram_chat_id_text_input")
        self.import_bulk_file_path_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.import_bulk_file_path_text_edit.setGeometry(QtCore.QRect(330, 10, 161, 31))
        self.import_bulk_file_path_text_edit.setStyleSheet("  border-color: #1de9b6;")
        self.import_bulk_file_path_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.import_bulk_file_path_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.import_bulk_file_path_text_edit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.import_bulk_file_path_text_edit.setObjectName("import_bulk_file_path_text_edit")
        self.sub_console_frame = QtWidgets.QFrame(self.centralwidget)
        self.sub_console_frame.setGeometry(QtCore.QRect(610, 0, 351, 91))
        self.sub_console_frame.setStyleSheet("  border-color: #1de9b6;")
        self.sub_console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sub_console_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sub_console_frame.setObjectName("sub_console_frame")
        self.sub_console_frame_text = QtWidgets.QTextEdit(self.sub_console_frame)
        self.sub_console_frame_text.setGeometry(QtCore.QRect(0, 0, 351, 91))
        self.sub_console_frame_text.setObjectName("sub_console_frame_text")
        self.main_console_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_console_frame.setGeometry(QtCore.QRect(210, 330, 581, 261))
        self.main_console_frame.setStyleSheet("  border-color: #1de9b6;")
        self.main_console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_console_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_console_frame.setObjectName("main_console_frame")
        self.console_text_edit = QtWidgets.QTextEdit(self.main_console_frame)
        self.console_text_edit.setGeometry(QtCore.QRect(0, 0, 581, 261))
        self.console_text_edit.setObjectName("console_text_edit")
        self.start_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(10, 580, 80, 31))
        self.start_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(110, 580, 80, 31))
        self.stop_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.stop_button.setObjectName("stop_button")
        self.setWebhook_button = QtWidgets.QPushButton(self.centralwidget)
        self.setWebhook_button.setGeometry(QtCore.QRect(890, 340, 80, 31))
        self.setWebhook_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.setWebhook_button.setObjectName("setWebhook_button")
        self.sendDocument_button = QtWidgets.QPushButton(self.centralwidget)
        self.sendDocument_button.setGeometry(QtCore.QRect(890, 430, 80, 31))
        self.sendDocument_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.sendDocument_button.setObjectName("sendDocument_button")
        self.getME_button = QtWidgets.QPushButton(self.centralwidget)
        self.getME_button.setGeometry(QtCore.QRect(800, 340, 80, 31))
        self.getME_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.getME_button.setObjectName("getME_button")
        self.sendPhoto_button = QtWidgets.QPushButton(self.centralwidget)
        self.sendPhoto_button.setGeometry(QtCore.QRect(800, 470, 80, 31))
        self.sendPhoto_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.sendPhoto_button.setObjectName("sendPhoto_button")
        self.sendMessage_button = QtWidgets.QPushButton(self.centralwidget)
        self.sendMessage_button.setGeometry(QtCore.QRect(800, 430, 80, 31))
        self.sendMessage_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.sendMessage_button.setObjectName("sendMessage_button")
        self.set_privacy_button = QtWidgets.QPushButton(self.centralwidget)
        self.set_privacy_button.setGeometry(QtCore.QRect(800, 520, 80, 31))
        self.set_privacy_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.set_privacy_button.setObjectName("set_privacy_button")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(800, 560, 80, 31))
        self.pushButton_7.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(890, 560, 80, 31))
        self.pushButton_8.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.console_text_response_input = QtWidgets.QTextEdit(self.centralwidget)
        self.console_text_response_input.setGeometry(QtCore.QRect(220, 600, 471, 31))
        self.console_text_response_input.setObjectName("console_text_response_input")
        self.console_text_response_button = QtWidgets.QPushButton(self.centralwidget)
        self.console_text_response_button.setGeometry(QtCore.QRect(700, 600, 80, 31))
        self.console_text_response_button.setStyleSheet("  border: 2px solid #1de9b6;\n"
"  border-radius: 4px;\n"
"  height: 32px;")
        self.console_text_response_button.setObjectName("console_text_response_button")
        DiamondDumper.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DiamondDumper)
        self.statusbar.setObjectName("statusbar")
        DiamondDumper.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(DiamondDumper)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 980, 22))
        self.menubar.setObjectName("menubar")
        self.menuDiamond_Sorter = QtWidgets.QMenu(self.menubar)
        self.menuDiamond_Sorter.setObjectName("menuDiamond_Sorter")
        self.menuConsole_Screen = QtWidgets.QMenu(self.menubar)
        self.menuConsole_Screen.setObjectName("menuConsole_Screen")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuBrowser = QtWidgets.QMenu(self.menubar)
        self.menuBrowser.setObjectName("menuBrowser")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setGeometry(QtCore.QRect(661, 101, 144, 156))
        self.menuAbout.setAccessibleName("")
        self.menuAbout.setTearOffEnabled(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/malware-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuAbout.setIcon(icon)
        self.menuAbout.setSeparatorsCollapsible(False)
        self.menuAbout.setToolTipsVisible(False)
        self.menuAbout.setObjectName("menuAbout")
        DiamondDumper.setMenuBar(self.menubar)
        self.actionaboutButton = QtWidgets.QAction(DiamondDumper)
        self.actionaboutButton.setMenuRole(QtWidgets.QAction.AboutRole)
        self.actionaboutButton.setObjectName("actionaboutButton")
        self.windows_menu_actionDiamondPad = QtWidgets.QAction(DiamondDumper)
        self.windows_menu_actionDiamondPad.setObjectName("windows_menu_actionDiamondPad")
        self.window_menu_actionPrefrences = QtWidgets.QAction(DiamondDumper)
        self.window_menu_actionPrefrences.setObjectName("window_menu_actionPrefrences")
        self.window_menu_actionRegex = QtWidgets.QAction(DiamondDumper)
        self.window_menu_actionRegex.setObjectName("window_menu_actionRegex")
        self.actionRegex_Cheat_Sheet = QtWidgets.QAction(DiamondDumper)
        self.actionRegex_Cheat_Sheet.setObjectName("actionRegex_Cheat_Sheet")
        self.actionHints_Tricks = QtWidgets.QAction(DiamondDumper)
        self.actionHints_Tricks.setObjectName("actionHints_Tricks")
        self.actionDataParsing = QtWidgets.QAction(DiamondDumper)
        self.actionDataParsing.setObjectName("actionDataParsing")
        self.actionDisplay_Console = QtWidgets.QAction(DiamondDumper)
        self.actionDisplay_Console.setObjectName("actionDisplay_Console")
        self.actionDisplay_HTTP_Client = QtWidgets.QAction(DiamondDumper)
        self.actionDisplay_HTTP_Client.setObjectName("actionDisplay_HTTP_Client")
        self.actionEnable_Everything = QtWidgets.QAction(DiamondDumper)
        self.actionEnable_Everything.setObjectName("actionEnable_Everything")
        self.actionLaunch_Browser = QtWidgets.QAction(DiamondDumper)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/diamond.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLaunch_Browser.setIcon(icon1)
        self.actionLaunch_Browser.setVisible(True)
        self.actionLaunch_Browser.setObjectName("actionLaunch_Browser")
        self.actionUndetected_Chrome = QtWidgets.QAction(DiamondDumper)
        self.actionUndetected_Chrome.setObjectName("actionUndetected_Chrome")
        self.actionShow_Widget_Functions = QtWidgets.QAction(DiamondDumper)
        self.actionShow_Widget_Functions.setObjectName("actionShow_Widget_Functions")
        self.actionInsomnia_HTTP_Client = QtWidgets.QAction(DiamondDumper)
        self.actionInsomnia_HTTP_Client.setObjectName("actionInsomnia_HTTP_Client")
        self.actionloadDirectory = QtWidgets.QAction(DiamondDumper)
        icon = QtGui.QIcon.fromTheme("accessories-text-editor")
        self.actionloadDirectory.setIcon(icon)
        self.actionloadDirectory.setMenuRole(QtWidgets.QAction.ApplicationSpecificRole)
        self.actionloadDirectory.setObjectName("actionloadDirectory")
        self.actionMembership = QtWidgets.QAction(DiamondDumper)
        self.actionMembership.setObjectName("actionMembership")
        self.actionTelegram_Group = QtWidgets.QAction(DiamondDumper)
        self.actionTelegram_Group.setObjectName("actionTelegram_Group")
        self.actionMentorship = QtWidgets.QAction(DiamondDumper)
        self.actionMentorship.setObjectName("actionMentorship")
        self.actionHomepage = QtWidgets.QAction(DiamondDumper)
        self.actionHomepage.setObjectName("actionHomepage")
        self.menuDiamond_Sorter.addAction(self.windows_menu_actionDiamondPad)
        self.menuDiamond_Sorter.addAction(self.window_menu_actionPrefrences)
        self.menuDiamond_Sorter.addAction(self.window_menu_actionRegex)
        self.menuDiamond_Sorter.addSeparator()
        self.menuDiamond_Sorter.addAction(self.actionShow_Widget_Functions)
        self.menuConsole_Screen.addAction(self.actionDisplay_Console)
        self.menuConsole_Screen.addSeparator()
        self.menuConsole_Screen.addAction(self.actionEnable_Everything)
        self.menuConsole_Screen.addSeparator()
        self.menuSettings.addAction(self.actionRegex_Cheat_Sheet)
        self.menuSettings.addAction(self.actionHints_Tricks)
        self.menuSettings.addAction(self.actionDataParsing)
        self.menuBrowser.addAction(self.actionLaunch_Browser)
        self.menuBrowser.addAction(self.actionUndetected_Chrome)
        self.menuBrowser.addSeparator()
        self.menuBrowser.addAction(self.actionInsomnia_HTTP_Client)
        self.menuAbout.addAction(self.actionHomepage)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionMembership)
        self.menuAbout.addAction(self.actionMentorship)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionTelegram_Group)
        self.menubar.addAction(self.menuDiamond_Sorter.menuAction())
        self.menubar.addAction(self.menuConsole_Screen.menuAction())
        self.menubar.addAction(self.menuBrowser.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(DiamondDumper)
        QtCore.QMetaObject.connectSlotsByName(DiamondDumper)
        # Display initial responses upon launching the script
        self.print_console_message("Reading database...")
        self.print_console_message("Importing information...")




















    def retranslateUi(self, DiamondDumper):
        _translate = QtCore.QCoreApplication.translate
        DiamondDumper.setWindowTitle(_translate("DiamondDumper", "DiamondSorter"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DiamondDumper", "No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DiamondDumper", "Token"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DiamondDumper", "Bot Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DiamondDumper", "Status"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DiamondDumper", "Submission Date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("DiamondDumper", "Last Checked Date"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("DiamondDumper", "Last Dumped Date"))
        self.submit_single_token_button.setText(_translate("DiamondDumper", "Submit"))
        self.sync_button.setText(_translate("DiamondDumper", "Sync"))
        self.import_bulk_button.setText(_translate("DiamondDumper", "Import Bulk"))
        self.bot_manager_text_input.setWhatsThis(_translate("DiamondDumper", "Bot Manager Token ID will be the bot that communicates with you from this panel."))
        self.bot_manager_text_input.setPlaceholderText(_translate("DiamondDumper", "Bot Manager Token ID"))
        self.single_token_submittion_text_input.setPlaceholderText(_translate("DiamondDumper", "Single Token Submission"))
        self.telegram_chat_id_text_input.setWhatsThis(_translate("DiamondDumper", "This is that channel or chat ID that you want your Bot Manager to be posting in.\n"
"If you want it set to just you - then set your user ID from @getID bot"))
        self.telegram_chat_id_text_input.setPlaceholderText(_translate("DiamondDumper", "Telegram Chat ID"))
        self.import_bulk_file_path_text_edit.setPlaceholderText(_translate("DiamondDumper", "Text File Path with Tokens"))
        self.start_button.setText(_translate("DiamondDumper", "Start"))
        self.stop_button.setText(_translate("DiamondDumper", "Stop"))
        self.setWebhook_button.setText(_translate("DiamondDumper", "Set Webhook"))
        self.sendDocument_button.setText(_translate("DiamondDumper", "Send Docs"))
        self.getME_button.setText(_translate("DiamondDumper", "Get Me"))
        self.sendPhoto_button.setText(_translate("DiamondDumper", "Send Photo"))
        self.sendMessage_button.setText(_translate("DiamondDumper", "Send Msgs"))
        self.set_privacy_button.setText(_translate("DiamondDumper", "Set Privacy"))
        self.pushButton_7.setText(_translate("DiamondDumper", "PushButton"))
        self.pushButton_8.setText(_translate("DiamondDumper", "PushButton"))
        self.console_text_response_button.setText(_translate("DiamondDumper", "Send"))
        self.menuDiamond_Sorter.setTitle(_translate("DiamondDumper", "Diamond Dumper - Telegram Bot Token Manager"))
        self.menuConsole_Screen.setTitle(_translate("DiamondDumper", "Console Screen"))
        self.menuSettings.setTitle(_translate("DiamondDumper", "Settings"))
        self.menuBrowser.setTitle(_translate("DiamondDumper", "Browser"))
        self.menuAbout.setTitle(_translate("DiamondDumper", "About"))
        self.actionaboutButton.setText(_translate("DiamondDumper", "aboutButton"))
        self.windows_menu_actionDiamondPad.setText(_translate("DiamondDumper", "Diamond Pad (Coming Soon)"))
        self.window_menu_actionPrefrences.setText(_translate("DiamondDumper", "Regex Creator (Coming Soon)"))
        self.window_menu_actionRegex.setText(_translate("DiamondDumper", "Expression Veiwer (Coming Soon)"))
        self.actionRegex_Cheat_Sheet.setText(_translate("DiamondDumper", "Regex Cheat Sheet"))
        self.actionHints_Tricks.setText(_translate("DiamondDumper", "Hints & Tricks"))
        self.actionDataParsing.setText(_translate("DiamondDumper", "DataParsing"))
        self.actionDisplay_Console.setText(_translate("DiamondDumper", "Display Console (Coming Soon)"))
        self.actionDisplay_HTTP_Client.setText(_translate("DiamondDumper", "Display HTTP Client"))
        self.actionEnable_Everything.setText(_translate("DiamondDumper", "Enable \"Everything\"(Coming Soon)"))
        self.actionLaunch_Browser.setText(_translate("DiamondDumper", "Launch Browser"))
        self.actionUndetected_Chrome.setText(_translate("DiamondDumper", "Undetected Chrome"))
        self.actionShow_Widget_Functions.setText(_translate("DiamondDumper", "Show Widget Functions (Coming Soon)"))
        self.actionInsomnia_HTTP_Client.setText(_translate("DiamondDumper", "Insomnia HTTP Client"))
        self.actionloadDirectory.setText(_translate("DiamondDumper", "loadDirectory"))
        self.actionMembership.setText(_translate("DiamondDumper", "Membership"))
        self.actionTelegram_Group.setText(_translate("DiamondDumper", "Telegram Group"))
        self.actionMentorship.setText(_translate("DiamondDumper", "Mentorship"))
        self.actionHomepage.setText(_translate("DiamondDumper", "Homepage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DiamondDumper = QtWidgets.QMainWindow()
    ui = Ui_DiamondDumper()
    ui.setupUi(DiamondDumper)
    DiamondDumper.show()
    sys.exit(app.exec_())
